# NumPY

### Import library


### Not recommended way

In [ ]:
import numpy
numpy.array([1, 2, 3])  krja krja


array([1, 2, 3])

In [ ]:
from numpy import *
array([1, 2, 3, 4])

array([1, 2, 3, 4])

### Recommended way:

In [ ]:
import numpy as np
np.array([1, 2])

array([1, 2])

###Arrays

In [ ]:
a = np.array([1, 2, 3, 4])
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
f = np.array([1.2, 1.3, 1.4])
f.dtype

dtype('float64')

In [ ]:
b = np.array([1, 'abc', True])
b.dtype
#b.dtype.type


dtype('<U21')

In [ ]:
a[0]

1

In [ ]:
a[0] = 10
a

array([10,  2,  3,  4])

In [ ]:
a[0] = 11.5
a

array([11,  2,  3,  4])

In [ ]:
a[0] = "string"

ValueError: ignored

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
a.size

4

In [ ]:
a = np.array([[11, 12, 13], [21, 22, 23]])
a

array([[11, 12, 13],
       [21, 22, 23]])

In [ ]:
a.shape

In [ ]:
a[0,0]

In [ ]:
a[1,2]

####Array indexing

In [ ]:
#row
a[1,]

In [ ]:
#row
a[1, :]

In [ ]:
#column
a[:, 2]

In [ ]:
a[:, 0:2]

In [ ]:
a[0, 1:]

####Alternative options to create array 

[documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [ ]:
a = np.zeros((3, 5))
a

In [ ]:
a = np.ones((2,3,4))
a

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a = np.full((2, 3), 7)
a

In [ ]:
np.full_like(a, 11)

In [ ]:
a = np.arange(0, 10, 2)
a

###Operations with arrays 
### Universal functions (ufunc)

In [ ]:
a = np.ones((4))
a

In [ ]:
b = np.full_like(a, 2)
b

In [ ]:
np.add(a, b)

In [ ]:
a + b

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
a / b

In [ ]:
c = np.zeros((1,3))
np.cos(c)

### Vectorization

All previous operations are element-wise and were called without loops. This because all of them are vectorized operations.

In [ ]:
a_list = [i for i in range(100000)]
type(a_list)

In [ ]:
from datetime import datetime
start = datetime.now()
a2_list = [a + 2 for a in a_list] 
end = datetime.now()
loop_time = (end-start).total_seconds()
print(loop_time)

In [ ]:
%%timeit
a2_list = [a + 2 for a in a_list] 

In [ ]:
a_arr = np.array(a_list)
type(a_arr)

In [ ]:
start = datetime.now()
a2_arr = a_arr + 2 
end = datetime.now()
vec_time = (end-start).total_seconds()
print(vec_time)

In [ ]:
%%timeit
a2_arr = a_arr + 2

In [ ]:
loop_time/vec_time

### Broadcasting

[Documentations](https://numpy.org/doc/stable/user/basics.broadcasting.html) 

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

* they are equal, or
* one of them is 1

In [ ]:
a = np.array([1, 1, 1])
a + 1

In [ ]:
a = np.ones((3, 2))
a.shape

In [ ]:
b = np.array([5, 5])
b.shape

In [ ]:
a+b

In [ ]:
b = np.array([5, 5, 5])
a + b

### Arrays are mutable!!!

In [ ]:
a = np.array([1, 2, 3])
b = a
b

In [ ]:
b[1] = 11
b

In [ ]:
a

In [ ]:
b = a.copy()
b[1] = 111
b

In [ ]:
a